### ISSUE TITLE
Help with deployment

### ISSUE THREAD

**Issue by Viskus** [azerothcore/server-status#23]
This isn't a bug, it's just me looking for some assistance hopefully.
I have one server running AC and Acore-Api container and another server that I use for the website etc. I'm hoping to put this server status on said website, but unsure how to actually deploy it. I have edited the config file etc, I can confirm all ports open and listening etc, but not sure how to load the page?

**Comment by FrancescoBorzi** [comment]
@Viskus hello and welcome to AzerothCore. The GitHub issues are used only for bug reporting, if you need support please read:

http://www.azerothcore.org/wiki/How-to-ask-for-help
